// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBpnDcoAWz7r04YA3fPVgZhwAIOvmth8N0',
    appId: '1:344465135850:web:9f1e424c925f1f7c3adf93',
    messagingSenderId: '344465135850',
    projectId: 'luckyman-t-and-l',
    authDomain: 'luckyman-t-and-l.firebaseapp.com',
    storageBucket: 'luckyman-t-and-l.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCr_eddRxwiYwt-uZuI0P82f_oPvRRB-9Y',
    appId: '1:344465135850:android:926710db3c8504013adf93',
    messagingSenderId: '344465135850',
    projectId: 'luckyman-t-and-l',
    storageBucket: 'luckyman-t-and-l.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBKByQ03avkK3QgJHmxODYAYEhhbzsPZj0',
    appId: '1:344465135850:ios:227816dd86ef84fc3adf93',
    messagingSenderId: '344465135850',
    projectId: 'luckyman-t-and-l',
    storageBucket: 'luckyman-t-and-l.appspot.com',
    iosClientId: '344465135850-0in2jrb9c929g49vt0ifdfunhp9rnt70.apps.googleusercontent.com',
    iosBundleId: 'com.example.luckyman',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBKByQ03avkK3QgJHmxODYAYEhhbzsPZj0',
    appId: '1:344465135850:ios:227816dd86ef84fc3adf93',
    messagingSenderId: '344465135850',
    projectId: 'luckyman-t-and-l',
    storageBucket: 'luckyman-t-and-l.appspot.com',
    iosClientId: '344465135850-0in2jrb9c929g49vt0ifdfunhp9rnt70.apps.googleusercontent.com',
    iosBundleId: 'com.example.luckyman',
  );
}
